#!/bin/sh
# Load resources
# xrdb -merge .Xresources
# Set the background color
xsetroot -solid white

# remap capslock
xmodmap /home/zv/.xmodmaprc &

## Fire up apps
xscreensaver -no-splash &
xhost local:
xmonad

autocutsel &

if (xrandr | grep "HDMI2 connected"); then
    xrandr --output HDMI2 --left-of eDP1 --primary --auto
fi
