#!/bin/sh
# Load resources
# Set the background color
[[ $(xrandr | grep "HDMI2 connected") ]] &&  xrandr --output HDMI2 --left-of eDP1 --primary --auto

xsetroot -solid white

## Fire up apps
xscreensaver -no-splash &
xhost local:
xmonad

autocutsel &
ssh-add
