#!/bin/sh
# Load resources
# Set the background color
[[ $(xrandr | grep "HDMI2 connected") ]] &&  xrandr --output HDMI2 --left-of eDP1 --primary --auto

xsetroot -solid white

# remap capslock
xmodmap -e "remove Lock = Caps_Lock"
xmodmap -e "keysym Caps_Lock = Control_L"
xmodmap -e "add Control = Control_L"

## Fire up apps
xscreensaver -no-splash &
xhost local:
xmonad

autocutsel &
