# -*- mode: shell-script; sh-shell: bash; fill-column: 75; comment-column: 50; coding: utf-8 -*-
# .bashrc
# shellcheck shell=bash

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific environment
# shellcheck disable=SC2076
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi

export DENO_INSTALL="/home/zv/.deno"
PATH="$DENO_INSTALL/bin:$PATH"
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# XDG vars
export XDG_CACHE_HOME=${XDG_CACHE_HOME:=~/.cache}
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:=~/.config}

# Setup default temporary file location
if [[ -z "$TMPDIR" ]]; then
    TMPDIR="/tmp/$(whoami)"
    if [[ ! -d "$TMPDIR" ]]; then
        # shellcheck disable=SC2174
        mkdir -p -m 700 "$TMPDIR"
    fi
    export TMPDIR
fi

export HISTCONTROL=ignorespace:erasedups
export HISTSIZE=65535
export HISTFILE=~/.bash_history

# User specific aliases and functions
set -o vi
