#!/bin/sh
# Load resources
# Set the background color
# [[ $(xrandr | grep "HDMI2 connected") ]] &&  xrandr --output HDMI2 --left-of eDP1 --primary --auto

# xsetroot -gray

## Fire up apps
# xscreensaver -no-splash &

# Setup GPG Agent
# envfile="$HOME/.gnupg/gpg-agent.env"
# if [[ -e "$envfile" ]] && kill -0 $(grep GPG_AGENT_INFO "$envfile" | cut -d: -f 2) 2>/dev/null; then
#     eval "$(cat "$envfile")"
# else
#     eval "$(gpg-agent --daemon --enable-ssh-support --write-env-file "$envfile")"
# fi
#
# export GPG_AGENT_INFO  # the env file does not contain the export statement
# export SSH_AUTH_SOCK   # enable gpg-agent for ssh
#
# xmodmap ${HOME}/.xmodmaprc
setxkbmap -layout us -option ctrl:nocaps -option ctrl:ralt_rctrl -option ctrl:rctrl_ralt
# Run gpg-agent-wrapper to SSH using our yubikey
# source $HOME/.gnupg/gpg-agent-wrapper

# Compton may no longer be needed.
# compton
