# -*- mode: shell-script; fill-column: 75; comment-column: 50; -*-
# Build
export AR=ar

# Language
if [[ -z "$LANG" ]]; then
	export LANG='en_US.utf8'
fi
export LC_CTYPE=$LANG

# 10 years I've been listenining to this list prompt and today I am fucking done!
export LISTPROMPT=''

# XDG vars
export XDG_CACHE_HOME=${XDG_CACHE_HOME:="$HOME/.cache/"}
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:="$HOME/.config/"}

# Don't automatically rename my windows in screen/tmux
export DISABLE_AUTO_TITLE="true"

export EDITOR='vim'

# Environment
export GREP_COLORS="37;45"

# Ensure path arrays do not contain duplicates.
typeset -gU fpath mailpath path cdpath

# Paths
path=(
	/usr/local/bin
	/usr/local/sbin
	$path
	$HOME/.cargo/bin
	$HOME/.local/bin
)

# Remove all empty directories from the path
# for np ($path) if [[ ! -d $np ]] path=(${path#$np})
if [[ -d /usr/local/cuda/lib64 ]]; then
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64
fi

# Load our completion functions
fpath=(
	$HOME/.zsh/completion
	$HOME/.zsh/completion/rust-completion
	$HOME/.zsh/functions
	$HOME/.zsh/zsh-completions/src
	$fpath
)

# Temporary Files
if [[ ! -d "$TMPDIR" ]]; then
	export TMPDIR="/tmp/$LOGNAME"
	mkdir -p -m 700 "$TMPDIR"
fi
export TMPPREFIX="${TMPDIR%/}/zsh"

# Font Config
if [[ "$OSTYPE" == linux-gnu ]]; then
	export FONTCONFIG_PATH=${FONTCONFIG_PATH:=/etc/fonts}
fi

# virtualenvwrapper
export WORKON_HOME="$HOME/.local/environments"
