#!/usr/bin/zsh
# -*- mode: shell-script; sh-shell: zsh; fill-column: 75; comment-column: 50; coding: utf-8 -*-

# Locale
export TZ=${TZ:=America/Los_Angeles}
export LANG=${LANG:=en_US.UTF8}
export LC_CTYPE="$LANG"

# Use default prompt when paging through completion lists
export LISTPROMPT=''

# XDG vars
export XDG_CACHE_HOME=${XDG_CACHE_HOME:=~/.cache}
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:=~/.config}

# Don't automatically rename my windows in screen/tmux
export DISABLE_AUTO_TITLE=true

# Paths
path=(
    /usr/local/bin
    /usr/local/sbin
    $path
    ~/.local/bin
)

# Load our completion functions
fpath=(
    ~/.zsh/zsh-completions/src
    ~/.zsh/functions
    $fpath
)

# Ensure path arrays do not contain duplicates.
typeset -gU fpath mailpath path cdpath

# Temporary Files
if [[ ! -d "$TMPDIR" ]]; then
    TMPDIR="/tmp/$(whoami)"
    export TMPDIR
    # shellcheck disable=SC2174
    mkdir -p -m 700 "$TMPDIR"
fi

export TMPPREFIX="${TMPDIR%/}/zsh"

# Font Config
if [[ "$OSTYPE" == linux-gnu ]]; then
    export FONTCONFIG_PATH=${FONTCONFIG_PATH:=/etc/fonts}
fi

export EDITOR="${commands[vim]-${commands[vi]}}"
export VISUAL="$EDITOR"
export PAGER="${commands[less]-${EDITOR}}"

# virtualenvwrapper
export WORKON_HOME=~/.local/environments

# Java
export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on"

