# -*- mode: shell-script; fill-column: 75; comment-column: 50; -*-
# Language
if [[ -z "$LANG" ]]; then
	export LANG='en_US.utf8'
fi
export LC_CTYPE="$LANG"

# XDG vars
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache/}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config/}"

# Don't automatically rename my windows in screen/tmux
export DISABLE_AUTO_TITLE="true"

export EDITOR='vim'

# Paths
path=(
	/usr/local/bin
	/usr/local/sbin
  $path
	$HOME/.local/bin
	/usr/local/go/bin
	/usr/local/node/bin
)

# Load our completion functions
fpath=(
	$HOME/.zsh/completion
	$HOME/.zsh/zsh-completions/src
	$HOME/.zsh/functions
	$fpath
)

# Remove all empty directories from the path
# for np ($path) if [[ ! -d $np ]] path=(${path#$np})
if [[ -d /usr/local/cuda/lib64 ]]; then
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64
fi

# Remove all duplicates in path scalars
typeset -gU fpath mailpath path cdpath manpath

# Temporary Files
if [[ ! -d "$TMPDIR" ]]; then
	export TMPDIR="/tmp/$LOGNAME"
	mkdir -p -m 700 "$TMPDIR"
fi
export TMPPREFIX="${TMPDIR%/}/zsh"

# Font Config
if [[ "$OSTYPE" == linux-gnu ]]; then
	export FONTCONFIG_PATH=${FONTCONFIG_PATH:=/etc/fonts}
fi

# Rust
if (( $+commands[rustc] )); then
    export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"
fi

# Java
export _JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on"
